title: Neil Orzechowski
email: nvorzech@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer
#gem install -n /usr/local/bin jekyll
domain: norzechowski.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://norzechowski.github.io  # the base hostname and protocol for your site, e.g. http://example.com
twitter_username: NVOrzech
github_username:  NOrzechowski

# Build settings
theme: minima
plugins:
#  - jekyll-feed
  - jekyll-postcss
  - farady-retry


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include: 
  - node_modules/ 

sass:
  load_paths:
    - _sass/
    - node_modules/
  # style: compressed